version: '3.9'
services:
  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  web:
    build: .
    command: uvicorn api.main_api:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8008:8000
    depends_on:
      - db
volumes:
  db:
    driver: local